config/routes.rb
Coincooler::Application.routes.draw do

  resources :uploads
 	resources :freezers, only: [:new, :create, :show]
 	resources :inspectors, only: [:new, :create, :addresses, :private_keys]

  root                                to: 'static#home'

  match "/home",                      to: 'static#home',              via: :get
  match "/dieharder",                 to: 'static#dieharder',         via: :get 
 
  match "/freeze",  				          to: 'freezers#new',   					via: :get
  match "/new_keys",                  to: 'freezers#show',        		via: :get
  match	"/download",				          to: 'freezers#download',				via: :get
  match "/download_row",              to: 'inspectors#download',      via: :get
  match "/download_up",               to: 'uploads#download',         via: :get
  match "/old_inspect",	              to: 'inspectors#new',           via: :get
  match "/old_inspect_addresses",     to: 'inspectors#addresses',     via: :get
  match "/old_inspect_keys",          to: 'inspectors#show',          via: :get

  match "/uploads",                   to: 'uploads#index',            via: :get
  match "/inspect",                   to: 'uploads#inspect',          via: :post
  match "/inspect_keys",              to: 'uploads#keys',             via: :get
  match "/inspect_addresses",         to: 'uploads#addresses',        via: :get
  
end

app/controllers/freezers_controller.rb
class FreezersController < ApplicationController
	require 'rqrcode'
	before_filter :clear_pk, only: [:create, :show]
	before_filter :clear_flash_messages
	before_filter	:redirect_home,						only: [:show, :download]

  def new
		@title=freeze_page_title
	end

	def create
		@title=freeze_page_title
		howmany=params[:howmany].to_i
		$split = params[:split].to_s
		$ssss={n: params[:ssss_n].to_i,k: params[:ssss_k].to_i}
		if valid_params?(howmany,$ssss)
			keys=KeyGenerator.new(howmany).keys
			@qm=Quartermaster.new(keys,params[:password].strip,$ssss)
			@qm.dump_files
		redirect_to new_keys_path
		else
			flash.now[:error] = build_validation_message(howmany,$ssss)
			render 'new'
		end
	end

  def show
    flash.now[:hot] = hot_message if HOT
  	@password= CSV.read(password_file_path('csv'))[1][0]
  	@expose=params[:expose]
  	# sleep 5 if (DEBUG) # this is to make it feel like the PI
  	@n=$ssss[:n]
  	@title=private_keys_title
    @data=CSV.read(private_keys_file_path('csv',false))
    @keys=build_private_keys_hash_array(@data)
    @remote = (AJAXON && COPY && all_files_there?)
    flash.now[:info] = instructions_flash unless @remote
  end

  def download
  	begin
  		if COPY
  			copy_files
  		else
  			download_files
  		end
		rescue => e
			Rails.logger.info('* * * * * *'+e.to_s)
			if e.to_s.scan(/Input\/output error - \/media\/usb\d+\/Cold_Storage/).blank?
				logger.warn(e.to_s)
				flash[:error]= {message: missing_file_error,id: 'missing_file'}
				redirect_to home_path
			else
				flash[:danger] = {message: no_usb_message,title: 'Insert a USB drive', id:'no_usb'}
				redirect_to new_keys_path
			end
		end
  end


  private

  	def copy_files
			unless usb_attached?
				cookies[:copy] = 'no_usb'
				flash[:danger] = {message: no_usb_message,title: 'Insert a USB drive', id:'no_usb'}
				redirect_to new_keys_path
			else
				set_copy_cookie
				case params[:download]
				when /addresses/
					origin=public_addresses_file_path('csv',false)
					target=public_directory_path(true)+addresses_file_name+'.csv'
					FileUtils.mkdir_p File.dirname(target)
			  	FileUtils.cp(origin,target)
			  	flash[:success] = {message: "Bitcoin addresses"+success_copy_suffix,title: success_copy_title(cold_storage_directory_name),id: 'addr_download_success'}
			  when 'unencrypted_private_keys'
			  	origin = private_keys_file_path('csv',false)
			  	target = unencrypted_directory_path(true)+private_keys_file_name+'.csv'
			  	FileUtils.mkdir_p File.dirname(target)
			  	FileUtils.cp(origin,target)
			  	flash[:success] = {message: "NON-ENCRYPTED private keys"+success_copy_suffix,title: success_copy_title(cold_storage_directory_name),id: 'plain_download_success'}
			  when 'encrypted_private_keys'
			  	origin = private_keys_file_path('csv',true)
			  	target = encrypted_directory_path(true)+private_keys_file_name+'.csv'+encrypted_file_suffix
			  	FileUtils.mkdir_p File.dirname(target)
			  	FileUtils.cp(origin,target)
			  	flash[:success] = {message: "Encrypted private keys"+success_copy_suffix,title: success_copy_title(cold_storage_directory_name),id: 'encrypted_download_success'}
				when 'password'
					origin=password_file_path('csv',false)
					target=encrypted_directory_path(true)+password_file_name+'.csv'
					FileUtils.mkdir_p File.dirname(target)
			  	FileUtils.cp(origin,target)
			  	flash[:success] = {message: "Password"+success_copy_suffix,title: success_copy_title(cold_storage_directory_name),id: 'pass_download_success'}
			  when 'password_share'
			  	origin = password_shares_path(params[:share].to_i)
			  	target = encrypted_directory_path(true) +password_share_file_name + '_' + params[:share].to_i.to_s + '.csv'
			  	FileUtils.mkdir_p File.dirname(target)
			  	FileUtils.cp(origin,target)
			  	flash[:success] = {message: "#{params[:share].to_i.ordinalize} password share" +success_copy_suffix,title: success_copy_title(cold_storage_directory_name),id: "share_#{params[:share].to_s}_download_success"}
			  else
			  	redirect_to home_path
			  end
			  redirect_to new_keys_path
			end
  	end

  	def download_files
 	  	case params[:download]
	  	when /addresses/
		  	send_file public_addresses_file_path('csv',false), filename: addresses_file_name+".csv"
		  when 'unencrypted_private_keys'
		  	send_file private_keys_file_path('csv',false), filename: private_keys_file_name+".csv"
		  when 'encrypted_private_keys'
		  	send_file private_keys_file_path('csv',true), filename: private_keys_file_name+".csv"+encrypted_file_suffix
	  	when 'password'
		  	send_file password_file_path('csv',false), filename: password_file_name+".csv"
		  when 'password_share'
		  	send_file password_shares_path(params[:share].to_i), filename: password_share_file_name+'_'+params[:share]+'.csv'
		  else
		  	redirect_to home_path
		  end
  	end

	  def freezers_params
	    params.require(:keys).permit(:howmany, :password)
	  end

	  def clear_flash_messages
	  	flash[:error].clear if flash[:error]
	  end

	  def redirect_home
	  	unless all_files_there?
				logger.warn('Not all coldstorage files were found.')
				cookies[:copy] = 'missing_files'
		  	flash[:error]= {message: missing_file_error,id: 'missing_file'}
		  	redirect_to home_path
	  	end
	  end
	  def build_validation_message(howmany,ssss_hash)
	  	message=""
	  	message << addresses_range_notice + ". " unless (1..KEYS_LIMIT).include?(howmany)
	  	message << at_least_two_shares_flash + ". " unless (2..SHARES_LIMIT).include?(ssss_hash[:n]) && (2..SHARES_LIMIT).include?(ssss_hash[:k])
	  	message << k_not_smaller_than_n_flash + ". " unless ssss_hash[:k]<ssss_hash[:n]
	  	return message
	  end
	  def valid_params?(howmany,ssss_hash)
	  	(1..KEYS_LIMIT).include?(howmany) && (2..SHARES_LIMIT).include?(ssss_hash[:n]) && (2..SHARES_LIMIT).include?(ssss_hash[:k]) && ssss_hash[:k]<ssss_hash[:n]
	  end
	  def instructions_flash
			if COPY
				{message: "#{'Insert a USB stick and' unless usb?} Download your cold storage files #{'to the USB stick' if usb?}", hide: false,id: 'instruction',close: false}
			else
				{message: "Use the Download buttons to download your cold storage files", hide: false,id: 'instruction_fc',close: true}
			end
	  end
end


# `mount`.split("\n").grep(/media\/usb/)[0].split(/media\/usb/)[1].split(/type/)[0].to_i
# /(\/media\/usb)(\d+)(\s+type)/.match(`mount`)[2]
# regy=/(\/media\/usb)(\d+)(\s+type)/
# `mount`.scan(regy).map{|x| p x[1].to_i}

app/helpers/freezers_helper.rb
module FreezersHelper

	def get_css_from_file
		file = File.join(Rails.root, 'app/helpers/download.css')
		File.read(file)
	end

	def inject_css(html_string,css_string=get_css_from_file)
		remove_tag=html_string[0..-(' </html>'.length)]
		insert_css=remove_tag<<'<style type="text/css">'<<css_string<<'</style></html>'		
	end

end

app/views/freezers/_advanced_options.slim
div#collapse.collapse
	= render 'howmany_addresses', array: (1..KEYS_LIMIT).to_a
	= render 'shared/password', pholder: enter_password_placeholder
	= render 'ssss'
= javascript_include_tag 'noscroll'

app/views/freezers/_download_addr_button.slim
= link_to(download_path(download: :addresses),class: "btn btn-primary",id: "download_addr", remote: @remote ,title: download_addresses_title)
	i.icon-arrow-down.icon-white
	= ' '+download_addresses_button
= javascript_include_tag 'download_addr' if @remote
 

app/views/freezers/_download_flash.slim
/ = render 'layouts/flash', flash: [[:success, ['foobar','mytitle']],[:alert, 'foogaz']]
- flash = []
- message_array=[]
- @n.times do |n|
 - message_array << "#{(n+1).to_i.ordinalize} password share"	
- message_array.concat(["Bitcoin addresses","NON-ENCRYPTED private keys","Encrypted private keys","Password"])
- message_array.each do |prefix|
	- flash << [:success,{message: prefix+success_copy_suffix,title: success_copy_title(cold_storage_directory_name),hide: true,close: false}]
- flash << [:error, {message: no_usb_message, title: 'insert a USB drive',hide: true,id: 'no_usb_message',close: false}]
- flash << [:info, {message: "#{'Insert a USB stick and' unless usb?} Download your cold storage files #{'to the USB stick' if usb?}", hide: false,id: 'instruction',close: false}]
= render 'layouts/flash', flash: flash

app/views/freezers/_download_keys_button.slim
div.btn-group.bottom5 
  button#download_keys.btn.btn-primary.dropdown-toggle type='button' data-toggle='dropdown'
    i.icon-arrow-down.icon-white
    = "Download Keys"
    span.caret
  ul.dropdown-menu role='menu'    
    li.private title="#{download_unencrypted_title}"
      = link_to(download_path(download: :unencrypted_private_keys),class: "private",id: "download_plain", remote: @remote)
        i.icon-arrow-down
        = download_non_encrypted_link
    li title="#{download_password_title}"
      = link_to(download_path(download: :password),class: "private",id: "download_pswd", remote: @remote)
        i.icon-arrow-down
        = download_password_link        
    li.divider
    li title="#{download_encrypted_title}"
      = link_to(download_path(download: :encrypted_private_keys),class: "public",id: "download_enc", remote: @remote)
        i.icon-arrow-down
        = download_encrypted_link
    - unless $split.blank?
      li
        - @n.times do |n|
          = link_to(download_path(download: :password_share,share: "#{n+1}"),class: "public", id: "password_share_#{n+1}",remote: @remote, title: " #{if COPY then "Save" else "Download" end} a file containing the #{(n+1).to_i.ordinalize} share for the password #{"\n to a USB drive" if COPY}")
            i.icon-arrow-down
            = " Share ##{n+1}"


= javascript_include_tag 'download_keys' if @remote

app/views/freezers/_howmany_addresses.slim
= "Generate "
- pick = if params[:howmany] then params[:howmany] else KEYS_DEFAULT end
= select_tag(:howmany, options_for_select(array,selected: pick ), class: 'pulldown large')
= " Addresses for Cold Storage"

app/views/freezers/_howmany_ssss_k.slim
- pick = if params[:ssss_k] then params[:ssss_k] else DEFAULT_SSSK end
= select_tag(:ssss_k, options_for_select(array,selected: pick ), class: 'pulldown small')

app/views/freezers/_howmany_ssss_n.slim
- pick = if params[:ssss_n] then params[:ssss_n] else DEFAULT_SSSN end
= select_tag(:ssss_n, options_for_select(array,selected: pick ), class: 'pulldown small', onchange: "capSsssK(getSsssN());$('#ssss_k option:eq(0)').prop('selected', true);")

app/views/freezers/_setup_form.slim
.setup
	= form_tag :freezers do		
		= render 'submit'
		= render 'shared/advanced_link'
		= render 'shared/pbkdf_alert'
		= render 'advanced_options'

app/views/freezers/_ssss.slim
.left
	.form-group
		.col-sm-offset-2.col-sm-10
			.checkbox		
				= check_box_tag 'split', 'yes', false, id: "ssss_on", class: "ckbxposition"
				= label_tag("ssss_on") do
					= render 'ssss_inner'

app/views/freezers/_ssss_inner.slim
div#ssssinner
	| Split password into
	= render 'howmany_ssss_n', array: (3..SHARES_LIMIT).to_a
	| shares, require at least
	- upper = if params[:howmany_ssss_n] then params[:howmany_ssss_n] else SHARES_LIMIT end
	= render 'howmany_ssss_k', array: (2..upper).to_a
	| to recover

app/views/freezers/_submit.slim
= button_tag(type: "submit", id: "generate_button", class: "btn btn-primary btn-large", onclick: "#{if PI then 'pbkdfAlert();$(".tooltip").remove();' end}", title: generate_button_title, data: { disable_with: "<i class='icon-refresh icon-white'></i>&nbsp; #{generate_button_action}" } ) do
	i.icon-play.icon-white
	= ' '+generate_button

app/views/freezers/new.slim
- cache('freeze_form')	do
	.container
		= render 'setup_form'

app/views/freezers/show.slim
= render 'download_flash' if @remote
= render 'shared/private_keys'
= javascript_include_tag 'scroll'