config/routes.rb
Coincooler::Application.routes.draw do

  resources :uploads
 	resources :freezers, only: [:new, :create, :show]
 	resources :inspectors, only: [:new, :create, :addresses, :private_keys]

  root                                to: 'static#home'

  match "/home",                      to: 'static#home',              via: :get
  match "/dieharder",                 to: 'static#dieharder',         via: :get 
 
  match "/freeze",  				          to: 'freezers#new',   					via: :get
  match "/new_keys",                  to: 'freezers#show',        		via: :get
  match	"/download",				          to: 'freezers#download',				via: :get
  match "/download_row",              to: 'inspectors#download',      via: :get
  match "/download_up",               to: 'uploads#download',         via: :get
  match "/old_inspect",	              to: 'inspectors#new',           via: :get
  match "/old_inspect_addresses",     to: 'inspectors#addresses',     via: :get
  match "/old_inspect_keys",          to: 'inspectors#show',          via: :get

  match "/uploads",                   to: 'uploads#index',            via: :get
  match "/inspect",                   to: 'uploads#inspect',          via: :post
  match "/inspect_keys",              to: 'uploads#keys',             via: :get
  match "/inspect_addresses",         to: 'uploads#addresses',        via: :get
  
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :upload,
  :url => "/system/:class/:attachment/:id/:style/:basename.:extension",
  :path => ":rails_root/files/uploads/"+ID.to_s+"/system/:class/:attachment/:id/:style/:basename.:extension"

  do_not_validate_attachment_file_type :upload
  include Rails.application.routes.url_helpers
  
  def to_jq_upload
    {
      "name" => read_attribute(:upload_file_name),
      "size" => read_attribute(:upload_file_size),
      "url" => upload.url,
      "delete_url" => upload_path(self),
      "delete_type" => "DELETE" 
    }
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  # before_filter :set_tag, only: :process
  include InspectorsHelper
  include UploadHelper
  before_filter :clear_pk, only: [:inspect, :keys, :addresses]
  before_filter :clear_stale_uploads, only: :index
  before_filter :nuke_all_uploads_on_rp, only: :index

  def index
    @title=inspect_page_title
    @uploads = Upload.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads.map{|upload| upload.to_jq_upload } }
    end
  end

  def inspect
    @title=inspect_page_title
    @shares = get_shares(Upload.all)
    @password = get_password(Upload.all) || params[:password]
    encrypted = Upload.where("upload_file_name LIKE '%"+encrypted_file_suffix+"'")
    @upload = (encrypted[0] unless encrypted.blank?) || Upload.last
    # @upload = Upload.where("upload_file_name LIKE '%"+encrypted_file_suffix+"'")[0] unless @shares.blank?
    if there?(@upload)
      process_uploaded_file(@upload.upload,@password, @shares)
    else
      flash[:error]= {message: missing_file_error, delay_seconds: 5,id: 'missing_file'}
      # redirect_to home_path
      redirect_to uploads_path
    end
    # flash[:notice] = "Successfully created..."+@upload.upload_file_name.to_s if @upload
    # render 'index'
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html {
          render :json => [@upload.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render json: {files: [@upload.to_jq_upload]}, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  def keys
    @expose=params[:expose]
    @title = private_keys_title
    @keys = $keys
    @n=@keys.length
    @remote = (AJAXON && COPY)
    flash.now[:info] = instructions_flash unless @remote
  end

  def addresses
    @expose=params[:expose]
    @title = addresses_title
    @n=0
    @remote = (AJAXON && COPY)
    @keys = $keys
  end

  def download
    begin
      if COPY
        copy_uploaded_file(params[:download])
      else
        download_uploaded_file
      end
    rescue => e
      logger.warn(e.to_s)
      flash[:error]= {message: missing_file_error,delay_seconds: 5, id: 'missing_file'}
      redirect_to home_path
    end
  end

  private

    def upload_params
      params.require(:upload).permit(:upload)
    end
    def instructions_flash
      {message: "You can use the download buttons to download a private key #{'to your USB stick' if usb?}", hide: false,id: 'instruction',close: !COPY}
    end
    def copy_uploaded_file(addr_or_key)
      unless usb_attached?
        cookies[:copy] = 'no_usb'
        flash[:danger] = {message: no_usb_message,title: 'Insert a USB drive',delay_seconds: FLASH_DELAY_SECONDS,id: 'no_usb'}
      else
        set_copy_cookie
        file = Upload.last
        origin = file.upload.path
        filename = file.upload_file_name
        target=coldstorage_directory(true)+filename
        FileUtils.mkdir_p File.dirname(target)
        FileUtils.cp(origin,target)
        flash[:success] = {message: "#{filename} "+success_copy_suffix,title: success_copy_title(cold_storage_directory_name),delay_seconds: FLASH_DELAY_SECONDS,id: "download_upload"}
      end
      case addr_or_key
      when 'keys'
        redirect_to old_inspect_keys_path
      when 'addresses'
        redirect_to old_inspect_addresses_path
      end
    end
    def download_uploaded_file
      file = Upload.last
      filepath = file.upload.path
      filename = file.upload_file_name
      send_file filepath, filename: filename
    end
end

app/helpers/upload_helper.rb
module UploadHelper
	include PathHelper

	# def strip_url_to_absolute_path(upload_object_url)
	# 	url=(jquery_uploads_path(ID)+upload_object_url)
	# 	url[0..(url.index('?').to_i-1)]
	# end

	# def get_absolute_path(upload_object)
	# 	raise 'not an upload object' unless upload_object.class.to_s == 'Upload'
	# 	strip_url_to_absolute_path(upload_object.upload.url)
	# end

	def fresh?(upload_object)
		return false unless upload_object.class.to_s == 'Upload'
		((Time.now-upload_object.created_at)/1.minute).round<60
	end

	def there?(upload_object)
		return false unless upload_object.class.to_s == 'Upload'
		file_there?(upload_object.upload.path)
	end
	def get_shares(upload_object_array)		
    shares=''
    upload_object_array.each do |upload_object|
    	begin
	      data = CSV.read(upload_object.upload.path)
	      if share_csv_format?(data) then
		      share = data[1][0]
		      shares<<share+ " "      	
	      end
			rescue
			end	      
    end
    return shares.strip
	end
	def get_password(upload_object_array)		
    password=''
    upload_object_array.each do |upload_object|
    	begin
	      data = CSV.read(upload_object.upload.path)
	      if password_csv_format?(data) then
		      pass = data[1][0]
		      password<<pass
	      end
			rescue
			end	      
    end
    return password.strip unless password.blank?
	end	
end

app/views/uploads/_download_upload_button.slim
= link_to(download_up_path(download: params[:action]),class: "btn btn-primary",id: "download_upload", remote: @remote ,title: download_upload_title)
	i.icon-arrow-down.icon-white
	= ' '+download_upload_button
= javascript_include_tag 'download_upload' if @remote
 

app/views/uploads/_init_upload.html.erb
<script type="text/javascript" charset="utf-8">
  $( document ).ready(function() {
    $(function () {
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload();
        // 
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          var fu = $('#fileupload').data('blueimpFileupload'), 
            template;
          fu._adjustMaxNumberOfFiles(-files.length);
          console.log(files);
          template = fu._renderDownload(files)
            .appendTo($('#fileupload .files'));
          // Force reflow:
          fu._reflow = fu._transition && template.length &&
            template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
        });

    });
  });
  $( document ).ready(function() {
    $('#fileupload').fileupload();
    if (navigator.appVersion.match(/Midori/)) {        
        setAutoUpload();
        setMaxNumFiles(1);      
        setFakeObserverOnRp('table#uplist');
      } else {
        setAutoUpload();
        setMaxNumFiles(1);      
        setObserver('table#uplist');
    }
  });  
</script>

app/views/uploads/_jquery_upload.slim
= render 'uploads/upload'
= render 'uploads/upload_errors'
= render 'uploads/template_download'
= render 'uploads/template_upload'
= render 'uploads/init_upload'
= render 'shared/pbkdf_alert'

app/views/uploads/_template_download.html.erb
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2" class="separator"></td>
        {% } %}
      <td class="delete">
        <button id="delbut" class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}" onclick="$('#upload_password').prop('checked', false);">
          <i class="icon-trash icon-white"></i>          
          <span></span>
        </button>
        <input id="delall" type="checkbox" name="delete" value="1" >
      </td>
    </tr>
    {% } %}
</script>

app/views/uploads/_template_upload.html.erb
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">    
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td class="progbar">
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>

app/views/uploads/_upload.slim
.container#upload
  / h2.view_header
  /   = inspect_page_header
  = form_for Upload.new, :html => { :multipart => true, :id => "fileupload"  } do |f|
    /! The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload
    .row.fileupload-buttonbar
      .span7
        /! The fileinput-button span is used to style the file input field as button
        span#upbut.btn.btn-success.btn-large.fileinput-button 
          i.icon-arrow-up.icon-white
          span#upbutext ="#{upload_button}"
          = f.file_field :upload
        / button#start.btn.btn-primary.start type="submit" 
        /   i.icon-upload.icon-white
        /   span Start upload          
        / button#cancel.btn.btn-warning.cancel type="reset" 
        /   i.icon-ban-circle.icon-white
        /   span Cancel upload
        button#del_all.btn.btn-danger.delete.hide type="button" title="Delete all checked files" 
          i.icon-trash.icon-white
          span 
        input#upload_del_all.toggle.hide type="checkbox" title="Check all" 
      .span5
        /! The global progress bar
        / .progress.progress-success.progress-striped.active.fade
        /   .bar style="width:0%;" 
    /! The loading indicator is shown during image processing
    .fileupload-loading
    br
      /! The table listing the files available for upload/download
      table.table.table-striped#uplist
        tbody.files data-target="#modal-gallery" data-toggle="modal-gallery" 

app/views/uploads/_upload_errors.html.erb
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'  
  };
</script>

app/views/uploads/_upload_password.slim
div.checkbox style="margin-left:20;"
	div.input-xxlarge style="float:right;color:gray;"
		= label_tag "upload_password",' upload a password file'
	div.inline 
		= check_box_tag('upload_password',0,false, id: "upload_password", onclick: "togglePassUpload();")
	

app/views/uploads/_upload_shares.slim
div.checkbox style="margin-left:20;"
	div.input-xxlarge style="float:right;color:gray;"
		= label_tag "upload_shares",' upload password shares'
	div.inline 
		= check_box_tag('upload_shares',0,false,id: "upload_shares", onclick: "toggleShareUpload();")
	

app/views/uploads/addresses.slim
= render 'inspectors/download_flash' if @remote
= render 'shared/addresses', keys: @keys

app/views/uploads/index.slim
table#jqup.forcenter_horiz
	tr
		td
			= render 'jquery_upload'
= form_tag({action: :inspect}) do
	table#uptbl.forcenter_horiz
		tr#password.hide
			td
				= render 'shared/password', pholder: recover_passwd_placeholder 
			td style="padding-top:5;padding-bottom:7;"
				= render 'upload_password'
				= render 'upload_shares'								
		tr#recover.hide
			td
				= button_tag(type: "submit", id: "recover_button", class: "btn btn-primary btn-large", onclick: "#{if PI then 'pbkdfAlert();$(".tooltip").remove();' end}", title: recover_button_title, data: { disable_with: "<i class='icon-refresh icon-white'></i>&nbsp; #{recover_button_action}" } ) do
					= image_tag('sunglasses_white.png', size: "20")
					span#recbutext = ' '+recover_button

app/views/uploads/keys.slim
= render 'inspectors/download_flash' if @remote
= render 'shared/private_keys'