config/routes.rb
Coincooler::Application.routes.draw do

  resources :uploads
 	resources :freezers, only: [:new, :create, :show]
 	resources :inspectors, only: [:new, :create, :addresses, :private_keys]

  root                                to: 'static#home'

  match "/home",                      to: 'static#home',              via: :get
  match "/dieharder",                 to: 'static#dieharder',         via: :get 
 
  match "/freeze",  				          to: 'freezers#new',   					via: :get
  match "/new_keys",                  to: 'freezers#show',        		via: :get
  match	"/download",				          to: 'freezers#download',				via: :get
  match "/download_row",              to: 'inspectors#download',      via: :get
  match "/download_up",               to: 'uploads#download',         via: :get
  match "/old_inspect",	              to: 'inspectors#new',           via: :get
  match "/old_inspect_addresses",     to: 'inspectors#addresses',     via: :get
  match "/old_inspect_keys",          to: 'inspectors#show',          via: :get

  match "/uploads",                   to: 'uploads#index',            via: :get
  match "/inspect",                   to: 'uploads#inspect',          via: :post
  match "/inspect_keys",              to: 'uploads#keys',             via: :get
  match "/inspect_addresses",         to: 'uploads#addresses',        via: :get
  
end

app/views/layouts/_app_links.slim
- c = params[:controller]
- a = params[:action]
- freeze = (c=='freezers' && a=='new')
- inspect = (c=='uploads' && a=='index')

li 
	= link_to freeze_path, id: 'navbar_freeze', title: freeze_button_title, class: "#{'bevel' if freeze}" do
			i.icon-play.icon-white
li 
	= link_to uploads_path, id: 'navbar_upload', title: inspect_button_title, class: "#{'bevel' if inspect}" do
			i.icon-arrow-up.icon-white

app/views/layouts/_debug.slim
= debug(params)

app/views/layouts/_favicon.slim
= favicon_link_tag 'coincooler.ico'

app/views/layouts/_flash.html.erb
<div class="container center watch-head">
	<% flash.each do |key, value| %>
		<% message = '' %>
		<% title = '' %>
		<% if value.class==Hash %>
			<% message = value[:message].to_s %>
			<% title = value[:title].to_s %>
			<% hide = value[:hide].to_s %>
			<% rnd = rand(10000..99999).to_s %>
			<% delay = value[:delay_seconds].to_i %>
			<% id = value[:id].to_s %>
			<% id = if id.blank? then rnd else id end %>
			<% id = "flash_"+id %>
			<% close = value[:close].to_s %>
		<% else  %>
			<% message = value.to_s %>
		<% end %>
		<div class="alert alert-<%= key %> tight border" id="<%= id %>">
			<% unless close=='false' %>
				<a class="close" data-dismiss="alert">&#215;</a>
			<% end %>
			<%= content_tag(:div, message, class: "tight", title: title) unless [:keys].index(key) %> 
		</div>
		<% if hide=='true' %>
			<script type="text/javascript">
				$('#<%= id %>').hide();
			</script>
		<% elsif delay.to_i > 0 %>
			<script type="text/javascript">
				$('#<%= id %>').delay(parseInt('<%= delay*1000 %>')).fadeOut(2000)
			</script>
		<% end %>
	<% end %>
</div>

app/views/layouts/_header.slim
header.navbar.navbar-fixed-top.navbar-inverse.hide_on_download
  .navbar-inner
    .container
      = link_to(home_path, id: "logo", title: "#{home_link_title unless [root_path, home_path].include?(request.fullpath)}") do
      	= image_tag('coincooler-white.ico', size: "31", class: "logo")
      	= app_title
      nav
        ul#head-links.nav.pull-right
					= render 'layouts/app_links'

app/views/layouts/_includes.html.erb
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>  
<!--    <LINK href="custom.css" rel="stylesheet" type="text/css"> -->

app/views/layouts/_scripts.slim
= javascript_include_tag "scripts"

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.slim
- c = params[:controller]
doctype
html
  head
    title
      = full_title(@title)
    = render 'layouts/favicon'
    = render 'layouts/shim'
  body class="#{c}"
    = render 'layouts/includes'
    = render 'layouts/header'
    = render 'layouts/flash'
    = yield
    = render 'layouts/debug' if DEBUG
    = render 'layouts/scripts'
.background    